# This workflow will build a package using Maven and then publish it to GitHub packages when commits are pushed
# to the release branch.
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path and
# https://blog.frankel.ch/github-actions-maven-releases/

name: Release with Maven

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out project
      uses: actions/checkout@v2
    - name: Set up JDK 1.8 and configure Maven
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Create release and publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B release:prepare release:perform
